//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalGasAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaruralGasPrice: NaturalGasPredict
    {
        private Nullable<float> price;
        public Nullable<float> Price
        {
            get
            {
                return price;
            }
            set
            {
                price = value;
                GasPrice = value == null ? 0 : (float)value;
            }
        }
        public int NaturalGasPriceId { get; set; }
    }
}
