//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalGasAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaruralGasPrice: NaturalGasPredict
    {
        private Nullable<float> gasPrice;
        public Nullable<float> GasPrice
        {
            get
            {
                return gasPrice;
            }
            set
            {
                gasPrice = value;
                Price = (float)value;
            }
        }
        public int NaturalGasPriceId { get; set; }
    }
}
