//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaturalGasAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaruralGasPrice
    {
        public System.DateTime Date { get; set; }
        public float Price { get; set; }
    }
}
